version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Exposing the application port

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 # Use the latest stable version
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro